
import { supabase } from './supabaseClient';
import { Order } from '../types';

/**
 * Saves a single order to the database with relational items and splits.
 */
export const saveOrder = async (userId: string, order: Order) => {
  try {
    const isRealStore = order.storeLocation && order.items[0].storeId.length > 20;

    if (!isRealStore) {
        console.warn("Mock Store Order - Not saving to DB");
        return; 
    }

    // 1. Insert Parent Order
    // Note: We still save the 'items' JSON snapshot for quick frontend retrieval without complex joins,
    // satisfying the probable 'items jsonb not null' constraint on the parent table.
    const { data: orderData, error } = await supabase
      .from('orders')
      .insert({
        customer_id: userId,
        store_id: order.items[0].storeId, 
        status: 'placed',
        items: order.items, // Snapshot
        total_amount: order.total,
        delivery_address: order.deliveryAddress,
        delivery_lat: order.userLocation?.lat,
        delivery_lng: order.userLocation?.lng
      })
      .select()
      .single();

    if (error) throw error;
    if (!orderData) throw new Error("Order creation failed");

    // 2. Insert Order Items (Relational Data)
    // This uses the new 'order_items' table structure
    const orderItemsPayload = order.items.map(item => ({
        order_id: orderData.id,
        product_id: item.originalProductId, // FK to products
        store_id: item.storeId,             // FK to stores
        unit_price: item.price,
        quantity: item.quantity
        // subtotal is generated by DB
    }));

    const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItemsPayload);

    if (itemsError) {
        console.error("Error saving order items:", itemsError);
        // We don't throw here to ensure the order itself and payment splits are still recorded
        // allowing the flow to complete even if relational insertion hits a policy snag.
    }

    // 3. Insert Payment Splits
    // Customer pays everything (Items + Delivery) to Store.
    if (order.splits) {
        const { error: splitError } = await supabase
            .from('payment_splits')
            .insert({
                order_id: orderData.id,
                store_amount: order.splits.storeAmount,
                store_upi: order.splits.storeUpi,
                handling_fee: 0,
                admin_upi: order.splits.adminUpi,
                delivery_fee: order.splits.deliveryFee,
                driver_upi: order.splits.driverUpi,
                total_paid_by_customer: order.splits.storeAmount, 
                is_settled: true // FULLY SETTLED by Customer
            });
        
        if (splitError) console.error("Error saving splits:", splitError);
    }

  } catch (err) {
    console.error('Supabase save failed:', err);
    throw err;
  }
};

export const getUserOrders = async (userId: string): Promise<Order[]> => {
  try {
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .eq('customer_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;

    return data.map((row: any) => ({
        id: row.id,
        date: row.created_at,
        items: row.items, // Uses the JSON snapshot for fast rendering of lists
        total: row.total_amount,
        status: mapDbStatusToAppStatus(row.status),
        paymentStatus: 'PAID',
        mode: 'DELIVERY',
        deliveryType: 'INSTANT',
        storeName: 'Grocesphere Store', // Placeholder (In real app, fetch store name via join)
        storeLocation: { lat: 0, lng: 0 }, 
        userLocation: { lat: row.delivery_lat, lng: row.delivery_lng }
    })) as Order[];
  } catch (err) {
    console.error('Supabase fetch failed:', err);
    return [];
  }
};

export const subscribeToUserOrders = (userId: string, onUpdate: (payload: any) => void) => {
    return supabase
        .channel(`user-orders-${userId}`)
        .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'orders', filter: `customer_id=eq.${userId}` }, (payload) => onUpdate(payload.new))
        .subscribe();
};

const mapDbStatusToAppStatus = (dbStatus: string): Order['status'] => {
    switch (dbStatus) {
        case 'placed': return 'Pending';
        case 'accepted': return 'Pending';
        case 'packing': return 'Preparing';
        case 'ready': return 'Ready';
        case 'on_way': return 'On the way';
        case 'delivered': return 'Delivered';
        case 'picked_up': return 'Picked Up';
        case 'cancelled': return 'Cancelled';
        default: return 'Pending';
    }
};
